Update check-license.yml

diff --git a/.github/workflows/check-license.yml b/.github/workflows/check-license.yml
--- a/.github/workflows/check-license.yml
+++ b/.github/workflows/check-license.yml
@@ -57,5 +57,10 @@ jobs:
         id: boilerplate-manual
         if: github.event_name == 'workflow_dispatch'
         run: |
-          python check_recent_pr.py ${{ github.event.inputs.PRNumber }}
+          if ! [[ "${{ github.event.inputs.PRNumber }}" =~ ^[0-9]+$ ]] && [ "{{ github.event.inputs.PRNumber }}" != "All" ]
+          then
+            echo "INVALID PR Number ENTERED..."
+          else
+            python check_recent_pr.py ${{ github.event.inputs.PRNumber }}
+          fi
         working-directory: tools
